# pyTorch

```
uv pip install torch torchvision --index-url https://download.pytorch.org/whl/cu126
```

- 파이토치 튜토리얼 : https://colab.research.google.com/drive/1NYDe4aFBukpTY7iC9QBuFyny59OJx08r?usp=sharing
- cmd : nvidia-smi
- 파이토치는 버전 호환성이 중요
- tensor : 다차원 배열

In [ ]:
# pyTorch 잘 설치되었는지 확인 -> True 나오면 됨 (GPU 쓸 준비가 됨)
# cmd 창에서 nvidia-smi 써보기
import torch

torch.cuda.is_available()

True

In [2]:
torch.__version__

'2.8.0+cu126'

In [3]:
torch.tensor(5)

tensor(5)

In [4]:
torch.tensor([1, 2, 3])

tensor([1, 2, 3])

In [5]:
torch.tensor([[1, 2, 3], [4, 5, 6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [6]:
data = [1, 2, 3, 4, 5]
torch.tensor(data)

tensor([1, 2, 3, 4, 5])

In [7]:
import numpy as np

data = np.array([1, 2, 3, 4, 5])
torch.tensor(data)

tensor([1, 2, 3, 4, 5])

In [8]:
torch.ones(3)   # 안이 다 1로 채워진 데이터가 3개

tensor([1., 1., 1.])

In [9]:
torch.ones(3, 5)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [ ]:
torch.ones(512, 512)    # 이미지    1 : 흰색 / 0 : 검정색

tensor([[1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        ...,
        [1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.]])

In [11]:
torch.zeros(512, 512)

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])

In [ ]:
torch.eye(5)        # eye : 단위행렬을 만들어줌

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [13]:
torch.arange(1, 10)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
torch.arange(1, 10, 2)

tensor([1, 3, 5, 7, 9])

In [ ]:
torch.rand(5)       # 랜덤

tensor([0.5561, 0.3554, 0.2375, 0.5321, 0.2477])

In [16]:
data = torch.rand(3, 3, 3)
data

tensor([[[0.9245, 0.1653, 0.0511],
         [0.9348, 0.8911, 0.7170],
         [0.1831, 0.0522, 0.7169]],

        [[0.4917, 0.2367, 0.4289],
         [0.2476, 0.4778, 0.6647],
         [0.2154, 0.1779, 0.5941]],

        [[0.0730, 0.9086, 0.3391],
         [0.5575, 0.2821, 0.3539],
         [0.6283, 0.6831, 0.2561]]])

In [ ]:
data.dim()      # 차원의 수

3

## view : 차원 변경

- 컬러 -> 흑백(2차원) 으로 변경시켜 모델을 학습시킴
- 모델에 input 넣을 때 2차원으로 넣어줘야함

In [ ]:
data.view(9, 3) # 차원 변경

tensor([[0.9245, 0.1653, 0.0511],
        [0.9348, 0.8911, 0.7170],
        [0.1831, 0.0522, 0.7169],
        [0.4917, 0.2367, 0.4289],
        [0.2476, 0.4778, 0.6647],
        [0.2154, 0.1779, 0.5941],
        [0.0730, 0.9086, 0.3391],
        [0.5575, 0.2821, 0.3539],
        [0.6283, 0.6831, 0.2561]])

In [19]:
data.view(27)

tensor([0.9245, 0.1653, 0.0511, 0.9348, 0.8911, 0.7170, 0.1831, 0.0522, 0.7169,
        0.4917, 0.2367, 0.4289, 0.2476, 0.4778, 0.6647, 0.2154, 0.1779, 0.5941,
        0.0730, 0.9086, 0.3391, 0.5575, 0.2821, 0.3539, 0.6283, 0.6831, 0.2561])

In [20]:
data.view(3, 9)

tensor([[0.9245, 0.1653, 0.0511, 0.9348, 0.8911, 0.7170, 0.1831, 0.0522, 0.7169],
        [0.4917, 0.2367, 0.4289, 0.2476, 0.4778, 0.6647, 0.2154, 0.1779, 0.5941],
        [0.0730, 0.9086, 0.3391, 0.5575, 0.2821, 0.3539, 0.6283, 0.6831, 0.2561]])

In [21]:
data.view(9, -1)    # -1 : 열의 개수는 알아서 채워줌

tensor([[0.9245, 0.1653, 0.0511],
        [0.9348, 0.8911, 0.7170],
        [0.1831, 0.0522, 0.7169],
        [0.4917, 0.2367, 0.4289],
        [0.2476, 0.4778, 0.6647],
        [0.2154, 0.1779, 0.5941],
        [0.0730, 0.9086, 0.3391],
        [0.5575, 0.2821, 0.3539],
        [0.6283, 0.6831, 0.2561]])

In [22]:
data.view(-1)       # 한줄로 쭉 피기

tensor([0.9245, 0.1653, 0.0511, 0.9348, 0.8911, 0.7170, 0.1831, 0.0522, 0.7169,
        0.4917, 0.2367, 0.4289, 0.2476, 0.4778, 0.6647, 0.2154, 0.1779, 0.5941,
        0.0730, 0.9086, 0.3391, 0.5575, 0.2821, 0.3539, 0.6283, 0.6831, 0.2561])

In [23]:
data.shape

torch.Size([3, 3, 3])

In [24]:
data.dim()

3

In [25]:
data.dtype

torch.float32

## cuda

- 데이터가 GPU에 있는거랑 CPU에 있는건 다름
- 연산하려는 데이터가 모두 같은 GPU 공간에 있어야 하고, 학습데이터도, 모델도 다 동일 GPU에 있어야함

In [26]:
# 이건 꼭 외우기!
torch.cuda.is_available()

True

In [ ]:
torch.cuda.device_count()       # GPU 개수

1

In [31]:
torch.cuda.get_device_name(0)    # GPU 이름

'NVIDIA GeForce RTX 4070 Laptop GPU'

In [32]:
device = torch.device("cuda:1")
device

device(type='cuda', index=1)

In [33]:
data = torch.tensor([1, 2, 3])
data

tensor([1, 2, 3])

### GPU로 데이터 옮기기
1. .to("cuda")

In [34]:
data.to("cuda")     # GPU로 옮기기

tensor([1, 2, 3], device='cuda:0')

2. .cuda()

In [36]:
data1 = torch.tensor([1, 2, 3]).cuda()
data1

tensor([1, 2, 3], device='cuda:0')

In [37]:
data1.to("cpu")     # CPU로 옮기기

tensor([1, 2, 3])

### 연산

In [38]:
data

tensor([1, 2, 3])

In [39]:
data1

tensor([1, 2, 3], device='cuda:0')

In [40]:
data + data1

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

In [41]:
data = data.to("cuda")
data + data1

tensor([2, 4, 6], device='cuda:0')

In [42]:
data - data1

tensor([0, 0, 0], device='cuda:0')

In [43]:
data * data1

tensor([1, 4, 9], device='cuda:0')

In [44]:
data / data1

tensor([1., 1., 1.], device='cuda:0')

In [45]:
data = torch.tensor([[1, 2, 3], [4, 5, 6]])
data

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
data.min()          # 최소값

tensor(1)

In [ ]:
data.min(dim=0)     # 열에서 가장 작은값 & 위치

torch.return_types.min(
values=tensor([1, 2, 3]),
indices=tensor([0, 0, 0]))

In [ ]:
data.min(dim=1)     # 행에서 가장 작은값 & 위치

torch.return_types.min(
values=tensor([1, 4]),
indices=tensor([0, 0]))

In [49]:
data.max()

tensor(6)

In [50]:
data.max(dim=0)

torch.return_types.max(
values=tensor([4, 5, 6]),
indices=tensor([1, 1, 1]))

In [51]:
data.max(dim=1)

torch.return_types.max(
values=tensor([3, 6]),
indices=tensor([2, 2]))

In [52]:
data.dtype

torch.int64

dtype 변경

In [54]:
data = data.type(torch.float)

In [55]:
data.dtype

torch.float32

In [56]:
data.mean()

tensor(3.5000)

## 차원 맞추기

1. .view()

In [ ]:
image = torch.rand(3,128, 128)          # 차원 : 3
image = image.view(1, 3, 128, 128)      # 차원 : 4
image

tensor([[[[0.7692, 0.5627, 0.6810,  ..., 0.0850, 0.0940, 0.9269],
          [0.5166, 0.2053, 0.4322,  ..., 0.3754, 0.0675, 0.3732],
          [0.8382, 0.0145, 0.0035,  ..., 0.2034, 0.7710, 0.1570],
          ...,
          [0.9392, 0.1734, 0.6283,  ..., 0.5386, 0.6036, 0.6372],
          [0.8191, 0.1684, 0.7898,  ..., 0.0392, 0.4800, 0.8976],
          [0.2005, 0.2298, 0.6384,  ..., 0.9745, 0.3348, 0.0342]],

         [[0.1675, 0.7991, 0.8044,  ..., 0.6264, 0.2053, 0.5122],
          [0.5624, 0.0779, 0.8931,  ..., 0.4940, 0.0493, 0.3207],
          [0.8263, 0.1029, 0.5861,  ..., 0.1799, 0.0501, 0.9108],
          ...,
          [0.2895, 0.0609, 0.3387,  ..., 0.4349, 0.3444, 0.9233],
          [0.8704, 0.4471, 0.6808,  ..., 0.9430, 0.3670, 0.8034],
          [0.8245, 0.6328, 0.4264,  ..., 0.4509, 0.6595, 0.1994]],

         [[0.6366, 0.2271, 0.4116,  ..., 0.6353, 0.8916, 0.6365],
          [0.9736, 0.5036, 0.4820,  ..., 0.6113, 0.1562, 0.1721],
          [0.9838, 0.5445, 0.2146,  ..., 0

2. unsqueeze() : 길이가 1인 차원을 추가

In [59]:
image = torch.rand(3,128, 128)
image = image.unsqueeze(dim=0)  # 앞에 하나의 차원을 더 늘려줌

In [60]:
image.shape

torch.Size([1, 3, 128, 128])

In [ ]:
data = torch.rand(1, 128, 128)      # 여기서, 1은 아무의미 없음 -> 삭제
data

tensor([[[0.4641, 0.6823, 0.4156,  ..., 0.6790, 0.1414, 0.1502],
         [0.5557, 0.4780, 0.9340,  ..., 0.8175, 0.3192, 0.5412],
         [0.7861, 0.6868, 0.4222,  ..., 0.8413, 0.5188, 0.1999],
         ...,
         [0.9882, 0.1121, 0.6364,  ..., 0.0254, 0.4081, 0.3592],
         [0.6638, 0.3898, 0.0982,  ..., 0.2636, 0.2801, 0.2172],
         [0.5962, 0.3514, 0.1828,  ..., 0.9551, 0.7681, 0.5102]]])

3. squeeze() : 길이가 1인 차원 삭제

In [62]:
data = data.squeeze()
data.shape

torch.Size([128, 128])