# 딥러닝 회귀 모델 생성

```
uv add pandas
uv add scikit-learn
```

In [5]:
import pandas as pd

In [6]:
df = pd.read_csv("data/boston.csv")
df

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1    0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2    0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3    0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4    0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
501  0.06263   0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0  273.0   
502  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  273.0   
503  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  273.0   
504  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2.3889  1.0  273.0   
505  0.04741   0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  273.0   

     PTRATIO       B  LSTAT  MEDV  
0       15.3  396.90   4.98  24.0  
1       17.8  396.90   9.14  21.6  
2       17.8  392.83   4.03  34.7  
3       18.7  394.63   2.94  33.4  
4       18.7  396.90   5.33  36.2  
..       ...     ...    ...   ...  
501     21.0  391.99   9.67  22.4  
502     21.0  396.90   9.08  20.6  
503     21.0  396.90   5.64  23.9  
504     21.0  393.45   6.48  22.0  
505     21.0  396.90   7.88  11.9  

[506 rows x 14 columns]

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   CRIM     506 non-null    float64
 1   ZN       506 non-null    float64
 2   INDUS    506 non-null    float64
 3   CHAS     506 non-null    float64
 4   NOX      506 non-null    float64
 5   RM       506 non-null    float64
 6   AGE      506 non-null    float64
 7   DIS      506 non-null    float64
 8   RAD      506 non-null    float64
 9   TAX      506 non-null    float64
 10  PTRATIO  506 non-null    float64
 11  B        506 non-null    float64
 12  LSTAT    506 non-null    float64
 13  MEDV     506 non-null    float64
dtypes: float64(14)
memory usage: 55.5 KB


In [8]:
import torch

X_train = df.iloc[:,:13].values
# X_train = torch.tensor(X_train)       # tensor 로 변경 1
X_train = torch.FloatTensor(X_train)    # tensor 로 변경 2

y_train = df.iloc[:, -1].values
y_train = torch.FloatTensor(y_train)

In [9]:
import torch.nn as nn
from torch.optim.adam import Adam

# Adam : 최적화 함수(optimize func)
# input-layer : 13
# hidden-layer : 맘대로 (여기선 100으로 설정)
# output-layer : 1 (정답은 1개)
# 13 -> 100 -> 50 -> 1

model = nn.Sequential(
    nn.Linear(13, 100),       # input으로 들어가는 피처의 개수(13), 나온는 개수(100)
    nn.ReLU(),                # 활성화 함수
    nn.Linear(100, 50),
    nn.ReLU(),
    nn.Linear(50, 1)
)

model

Sequential(
  (0): Linear(in_features=13, out_features=100, bias=True)
  (1): ReLU()
  (2): Linear(in_features=100, out_features=50, bias=True)
  (3): ReLU()
  (4): Linear(in_features=50, out_features=1, bias=True)
)

In [10]:
df.shape

(506, 14)

In [11]:
for name, param in model.named_parameters() :
    print(f"Name : {name}\n")
    print(f"Shape : {param.shape}\n")
    print(f"Values : {param}\n")

Name : 0.weight

Shape : torch.Size([100, 13])

Values : Parameter containing:
tensor([[ 0.1839,  0.0966, -0.1421,  ..., -0.0711,  0.0840, -0.0952],
        [-0.2041, -0.1420,  0.0316,  ..., -0.1236, -0.1291,  0.2635],
        [ 0.0949, -0.1363, -0.1978,  ...,  0.1306, -0.1584,  0.1736],
        ...,
        [ 0.1415,  0.2434,  0.1328,  ...,  0.1908, -0.2196,  0.2000],
        [-0.0615,  0.2703, -0.0400,  ..., -0.1039, -0.1563, -0.1541],
        [-0.1505, -0.0848,  0.1190,  ..., -0.0991, -0.1231,  0.0595]],
       requires_grad=True)

Name : 0.bias

Shape : torch.Size([100])

Values : Parameter containing:
tensor([-0.2164, -0.1036, -0.0083,  0.2668,  0.2288, -0.0398,  0.0396,  0.0951,
        -0.0949,  0.1113,  0.0906, -0.0782, -0.0841,  0.2657,  0.0913, -0.1717,
        -0.2597,  0.1732,  0.0990,  0.2464,  0.0930, -0.0235,  0.0502, -0.0478,
        -0.1418, -0.1242,  0.0311, -0.2054, -0.1552,  0.0615, -0.1356,  0.1340,
        -0.0784, -0.0698,  0.2329, -0.1568, -0.0909,  0.2265, -0.0

In [12]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
device

device(type='cuda')

In [13]:
# GPU로 데이터 올리기
X_train = X_train.to(device)
y_train = y_train.to(device)
model = model.to(device)

In [ ]:
optim = Adam(model.parameters(), lr=0.001)  # 최적화함수
epochs = 200                                # 몇 번 학습 시킬지
criterion = nn.MSELoss()                    # 손실함수

for epoch in range(epochs) :
    optim.zero_grad()                   # 최적화함수 기울기 초기화
    y_pred = model(X_train)             # 예측값
    loss = criterion(y_pred, y_train)   # 손실함수
    loss.backward()                     # 역전파
    optim.step()                        # 최적화 (가중치 업데이트)

    print(f"loss : {loss.item()}")

c:\deep_learning\.venv\Lib\site-packages\torch\nn\modules\loss.py:616: UserWarning: Using a target size (torch.Size([506])) that is different to the input size (torch.Size([506, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)


loss : 780.7772827148438
loss : 385.27532958984375
loss : 172.17556762695312
loss : 107.21012878417969
loss : 133.53103637695312
loss : 191.47982788085938
loss : 231.47576904296875
loss : 236.1537628173828
loss : 213.1333770751953
loss : 176.9108428955078
loss : 140.39254760742188
loss : 112.73358154296875
loss : 98.5892105102539
loss : 96.86318969726562
loss : 104.08589935302734
loss : 115.15142059326172
loss : 124.96925354003906
loss : 130.0097198486328
loss : 128.96817016601562
loss : 122.57808685302734
loss : 113.01004791259766
loss : 103.04911804199219
loss : 95.1307601928711
loss : 90.80170440673828
loss : 90.56224822998047
loss : 93.57649993896484
loss : 97.5818862915039
loss : 100.45639038085938
loss : 101.07807159423828
loss : 99.40072631835938
loss : 96.33110809326172
loss : 92.98711395263672
loss : 90.20895385742188
loss : 88.59783935546875
loss : 88.2713851928711
loss : 88.94107055664062
loss : 90.06566619873047
loss : 91.0745849609375
loss : 91.55782318115234
loss : 91.359

In [15]:
# 학습된 가중치의 값
model.state_dict()

OrderedDict([('0.weight',
              tensor([[ 0.1798,  0.1026, -0.1365,  ..., -0.0652,  0.0868, -0.0875],
                      [-0.1679, -0.1420,  0.0643,  ..., -0.0956, -0.1156,  0.2872],
                      [ 0.0949, -0.1363, -0.1978,  ...,  0.1306, -0.1584,  0.1736],
                      ...,
                      [ 0.1409,  0.2375,  0.1358,  ...,  0.1939, -0.2203,  0.2046],
                      [-0.0615,  0.2703, -0.0400,  ..., -0.1039, -0.1563, -0.1541],
                      [-0.1479, -0.0780,  0.1241,  ..., -0.0930, -0.1179,  0.0659]],
                     device='cuda:0')),
             ('0.bias',
              tensor([-0.2078, -0.0642, -0.0083,  0.2547,  0.2184, -0.0398,  0.0267,  0.0970,
                      -0.1098,  0.1015,  0.0906, -0.0711, -0.0841,  0.2556,  0.1020, -0.1785,
                      -0.2597,  0.1640,  0.0841,  0.2464,  0.0965, -0.0241,  0.0502, -0.0478,
                      -0.1448, -0.0993,  0.0311, -0.2363, -0.1645,  0.0834, -0.1356,  0.1261,
  

In [16]:
# 배치 사용
from torch.optim.adam import Adam

optim = Adam(model.parameters(), lr=0.001)
epochs = 200
batch_size = 100
criterion = nn.MSELoss()

for epoch in range(epochs) :
    for temp in range(len(X_train)//batch_size) :
        s = temp * batch_size   # 0 * 100
        e = s + batch_size      # 100

        X = X_train[s:e]
        y = y_train[s:e]

        optim.zero_grad()
        y_pred = model(X)
        loss = criterion(y_pred, y)
        loss.backward()
        optim.step()

    print(f"loss : {loss.item()}")

c:\deep_learning\.venv\Lib\site-packages\torch\nn\modules\loss.py:616: UserWarning: Using a target size (torch.Size([100])) that is different to the input size (torch.Size([100, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)


loss : 267.0063781738281
loss : 38.133941650390625
loss : 31.8334903717041
loss : 50.75652313232422
loss : 40.99457550048828
loss : 34.81953048706055
loss : 38.86934280395508
loss : 47.053916931152344
loss : 38.989540100097656
loss : 39.30032730102539
loss : 43.941524505615234
loss : 39.99186325073242
loss : 38.092864990234375
loss : 40.12855529785156
loss : 39.493988037109375
loss : 38.62429428100586
loss : 39.74179458618164
loss : 39.51298141479492
loss : 38.89961242675781
loss : 39.206912994384766
loss : 38.97393035888672
loss : 38.68368148803711
loss : 38.84917068481445
loss : 38.77202224731445
loss : 38.679405212402344
loss : 38.74753952026367
loss : 38.57944107055664
loss : 38.445919036865234
loss : 38.452938079833984
loss : 38.39507293701172
loss : 38.36161804199219
loss : 38.34721374511719
loss : 38.288414001464844
loss : 38.26985549926758
loss : 38.253868103027344
loss : 38.21651077270508
loss : 38.21010971069336
loss : 38.19007873535156
loss : 38.169715881347656
loss : 38.177